# coding: utf-8

"""
    Divseek Canada MVP application API

    Implements all the calls necessary for finding genomic markers for germplasm, but doesn't conform to BrAPI.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Germplasm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'general_identifier': 'str',
        'taxonomy_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'general_identifier': 'general_identifier',
        'taxonomy_id': 'taxonomy_id'
    }

    def __init__(self, id=None, name=None, general_identifier=None, taxonomy_id=None):  # noqa: E501
        """Germplasm - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._general_identifier = None
        self._taxonomy_id = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.general_identifier = general_identifier
        self.taxonomy_id = taxonomy_id

    @property
    def id(self):
        """Gets the id of this Germplasm.  # noqa: E501


        :return: The id of this Germplasm.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Germplasm.


        :param id: The id of this Germplasm.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Germplasm.  # noqa: E501


        :return: The name of this Germplasm.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Germplasm.


        :param name: The name of this Germplasm.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def general_identifier(self):
        """Gets the general_identifier of this Germplasm.  # noqa: E501


        :return: The general_identifier of this Germplasm.  # noqa: E501
        :rtype: str
        """
        return self._general_identifier

    @general_identifier.setter
    def general_identifier(self, general_identifier):
        """Sets the general_identifier of this Germplasm.


        :param general_identifier: The general_identifier of this Germplasm.  # noqa: E501
        :type: str
        """
        if general_identifier is None:
            raise ValueError("Invalid value for `general_identifier`, must not be `None`")  # noqa: E501

        self._general_identifier = general_identifier

    @property
    def taxonomy_id(self):
        """Gets the taxonomy_id of this Germplasm.  # noqa: E501


        :return: The taxonomy_id of this Germplasm.  # noqa: E501
        :rtype: int
        """
        return self._taxonomy_id

    @taxonomy_id.setter
    def taxonomy_id(self, taxonomy_id):
        """Sets the taxonomy_id of this Germplasm.


        :param taxonomy_id: The taxonomy_id of this Germplasm.  # noqa: E501
        :type: int
        """
        if taxonomy_id is None:
            raise ValueError("Invalid value for `taxonomy_id`, must not be `None`")  # noqa: E501

        self._taxonomy_id = taxonomy_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Germplasm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
