# coding: utf-8

"""
    Divseek Canada MVP application API

    Implements all the calls necessary for finding genomic markers for germplasm, but doesn't conform to BrAPI.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QTL(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qtl_id': 'int',
        'locus_name': 'str',
        'trait_id': 'int',
        'locus_id': 'int'
    }

    attribute_map = {
        'qtl_id': 'qtl_id',
        'locus_name': 'locus_name',
        'trait_id': 'trait_id',
        'locus_id': 'locus_id'
    }

    def __init__(self, qtl_id=None, locus_name=None, trait_id=None, locus_id=None):  # noqa: E501
        """QTL - a model defined in Swagger"""  # noqa: E501

        self._qtl_id = None
        self._locus_name = None
        self._trait_id = None
        self._locus_id = None
        self.discriminator = None

        self.qtl_id = qtl_id
        if locus_name is not None:
            self.locus_name = locus_name
        self.trait_id = trait_id
        self.locus_id = locus_id

    @property
    def qtl_id(self):
        """Gets the qtl_id of this QTL.  # noqa: E501


        :return: The qtl_id of this QTL.  # noqa: E501
        :rtype: int
        """
        return self._qtl_id

    @qtl_id.setter
    def qtl_id(self, qtl_id):
        """Sets the qtl_id of this QTL.


        :param qtl_id: The qtl_id of this QTL.  # noqa: E501
        :type: int
        """
        if qtl_id is None:
            raise ValueError("Invalid value for `qtl_id`, must not be `None`")  # noqa: E501

        self._qtl_id = qtl_id

    @property
    def locus_name(self):
        """Gets the locus_name of this QTL.  # noqa: E501


        :return: The locus_name of this QTL.  # noqa: E501
        :rtype: str
        """
        return self._locus_name

    @locus_name.setter
    def locus_name(self, locus_name):
        """Sets the locus_name of this QTL.


        :param locus_name: The locus_name of this QTL.  # noqa: E501
        :type: str
        """

        self._locus_name = locus_name

    @property
    def trait_id(self):
        """Gets the trait_id of this QTL.  # noqa: E501


        :return: The trait_id of this QTL.  # noqa: E501
        :rtype: int
        """
        return self._trait_id

    @trait_id.setter
    def trait_id(self, trait_id):
        """Sets the trait_id of this QTL.


        :param trait_id: The trait_id of this QTL.  # noqa: E501
        :type: int
        """
        if trait_id is None:
            raise ValueError("Invalid value for `trait_id`, must not be `None`")  # noqa: E501

        self._trait_id = trait_id

    @property
    def locus_id(self):
        """Gets the locus_id of this QTL.  # noqa: E501


        :return: The locus_id of this QTL.  # noqa: E501
        :rtype: int
        """
        return self._locus_id

    @locus_id.setter
    def locus_id(self, locus_id):
        """Sets the locus_id of this QTL.


        :param locus_id: The locus_id of this QTL.  # noqa: E501
        :type: int
        """
        if locus_id is None:
            raise ValueError("Invalid value for `locus_id`, must not be `None`")  # noqa: E501

        self._locus_id = locus_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QTL):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
