# coding: utf-8

"""
    Divseek Canada MVP application API

    Implements all the calls necessary for finding genomic markers for germplasm, but doesn't conform to BrAPI.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Query(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'trait_id': 'int',
        'germplasm_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'trait_id': 'traitID',
        'germplasm_id': 'germplasmID'
    }

    def __init__(self, id=None, trait_id=None, germplasm_id=None):  # noqa: E501
        """Query - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._trait_id = None
        self._germplasm_id = None
        self.discriminator = None

        self.id = id
        self.trait_id = trait_id
        self.germplasm_id = germplasm_id

    @property
    def id(self):
        """Gets the id of this Query.  # noqa: E501


        :return: The id of this Query.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Query.


        :param id: The id of this Query.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def trait_id(self):
        """Gets the trait_id of this Query.  # noqa: E501


        :return: The trait_id of this Query.  # noqa: E501
        :rtype: int
        """
        return self._trait_id

    @trait_id.setter
    def trait_id(self, trait_id):
        """Sets the trait_id of this Query.


        :param trait_id: The trait_id of this Query.  # noqa: E501
        :type: int
        """
        if trait_id is None:
            raise ValueError("Invalid value for `trait_id`, must not be `None`")  # noqa: E501

        self._trait_id = trait_id

    @property
    def germplasm_id(self):
        """Gets the germplasm_id of this Query.  # noqa: E501


        :return: The germplasm_id of this Query.  # noqa: E501
        :rtype: int
        """
        return self._germplasm_id

    @germplasm_id.setter
    def germplasm_id(self, germplasm_id):
        """Sets the germplasm_id of this Query.


        :param germplasm_id: The germplasm_id of this Query.  # noqa: E501
        :type: int
        """
        if germplasm_id is None:
            raise ValueError("Invalid value for `germplasm_id`, must not be `None`")  # noqa: E501

        self._germplasm_id = germplasm_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Query):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
