# coding: utf-8

"""
    Divseek Canada MVP application API

    Implements all the calls necessary for finding genomic markers for germplasm, but doesn't conform to BrAPI.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query import Query  # noqa: E501
from swagger_client.rest import ApiException


class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuery(self):
        """Test Query"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query.Query()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
